# Project information
site_name: 'ticktock documentation'
site_description: 'Simple Python code metering library'

nav:
  - Home: 'index.md'
  - Using clocks: 'using_clocks.md'
  - Customize output: 'customize.md'
  - Advanced topics:
    - Clocks: 'clocks.md'
    - Collection: 'collection.md'
    - Renderer: 'rendering.md'

theme:
  name: 'material'

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - meta
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  # - git-revision-date-localized

repo_name: 'victorbenichoux/ticktock'
repo_url: 'https://github.com/victorbenichoux/ticktock'
extra:
  repo_icon: 'github'

